name: pdf_fork
description: A fork from https://github.com/DavBfr/dart_pdf
homepage: https://github.com/insinfo/dart_pdf

version: 3.8.3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  archive: ">=3.1.0 < 4.0.0"
  barcode: ">=2.0.0 <3.0.0"
  crypto: ^3.0.0
  image: ">=3.0.1 <4.0.0"
  meta: ">=1.3.0 <2.0.0"
  path_parsing: ">=0.2.0 <2.0.0"
  vector_math: ^2.1.0
  xml: ">=5.1.0 <7.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ">=1.16.0 <2.0.0"
