name: pdf_fork
version: 3.10.5
description: A fork from https://github.com/DavBfr/dart_pdf
homepage: https://github.com/insinfo/dart_pdf

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  archive: ^3.1.0
  barcode: ">=2.2.3 <3.0.0"
  bidi: ^2.0.6
  crypto: ^3.0.0
  image: ^4.0.0
  meta: ">=1.3.0 <2.0.0"
  path_parsing: ">=0.2.0 <2.0.0"
  vector_math: ^2.1.0
  xml: ">=6.2.0 <7.0.0"

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ">=1.16.0 <2.0.0"
